### ISSUE TITLE
Just installed, got Warning

### ISSUE THREAD

**Issue by adamhathcock** [AlanWalk/quick-open-file#1]
"Target file is not found, please ensure extension settings is correct."

And it doesn't work :(

**Comment by alanwalk** [comment]
Hi, what 's your language?

**Comment by adamhathcock** [comment]
I didn't think I was trying any specific language.

**Comment by alanwalk** [comment]
This's a part of my user settings, it's used to match lua file.

```
    // Set which type you want to use peek. it's language id, not extension. 
    "quickOpenFile.peekLanguages": [
        "lua"
    ],

    // Set which file extension you want to include, ** is any extension.
    "quickOpenFile.extensionInclude": [
        "lua"
    ],

    // Set which folder you want to exclude.
    "quickOpenFile.folderExclude": [
        "node_modules",
        ".vscode"
    ],

    // Auto add suffix when search file(not allow peek), ** is match any suffix.
    "quickOpenFile.suffixList": [
        "_C",
        "_S"
    ]
```

**Comment by alanwalk** [comment]
![gif](https://cloud.githubusercontent.com/assets/4654826/18669928/eac34292-7f6f-11e6-9d0e-37f381819dca.gif)

**Comment by adamhathcock** [comment]
Now, I understand your question.  I just installed it and tried to instantly use it from the default shortcut and the command pallete.

I was hoping it just worked with anything open.  It would just be slower if there were a lot of files.

**Comment by adamhathcock** [comment]
Sorry, I misunderstood what this extension did.  I'll close this.

**Comment by alanwalk** [comment]
:)
