### ISSUE TITLE
auto-detect paths in require/import statements

### ISSUE THREAD

**Issue by pascalpp** [AlanWalk/quick-open-file#2]
I would love to be able to open files using the path under my cursor:
![image](https://user-images.githubusercontent.com/1355312/30655541-30bfb3ee-9dff-11e7-97a5-9215c779809e.png)

I've found that if i click on the last part of the path (the filename), then it does work, but would be nice if it could work anywhere in the path.

**Comment by alanwalk** [comment]
I'm sorry, peek operation can not match path.
"Fr43nk.seito-openfile", the extension is your needed, you can set a shortcut key to use it.
